export const scope1Config = {
    title: 'Direct Emissions Data Collection',
    description: 'Enter emissions from sources owned or controlled by your organization',
    headerLabel: 'SCOPE 1',
    categories: [
        {
            id: 'stationaryCombustion',
            name: 'Stationary Combustion',
            description: 'Emissions from burning fuels in stationary equipment (boilers, furnaces, generators)',
            icon: '🔥',
        },
        {
            id: 'mobileCombustion',
            name: 'Mobile Combustion',
            description: 'Emissions from company-owned or controlled vehicles',
            icon: '🚗',
        },
        {
            id: 'processEmissions',
            name: 'Process Emissions',
            description: 'Emissions from industrial processes (not from combustion)',
            icon: '⚙️',
        },
        {
            id: 'fugitiveEmissions',
            name: 'Fugitive Emissions',
            description: 'Leaks of refrigerants, gases, or other emissions',
            icon: '💨',
        },
    ],
    initialData: {
        stationaryCombustion: {
            'natural-gas': { name: 'Natural Gas (kWh)', value: '', unit: 'kWh', completed: false },
            'gas-oil': { name: 'Gas Oil (litres)', value: '', unit: 'litres', completed: false },
            'diesel': { name: 'Diesel (litres)', value: '', unit: 'litres', completed: false },
            'fuel-oil': { name: 'Fuel Oil (litres)', value: '', unit: 'litres', completed: false },
            'lpg': { name: 'LPG (litres)', value: '', unit: 'litres', completed: false },
            'coal': { name: 'Coal (tonnes)', value: '', unit: 'tonnes', completed: false },
            'wood-pellets': { name: 'Wood Pellets (tonnes)', value: '', unit: 'tonnes', completed: false },
            'wood-chips': { name: 'Wood Chips (tonnes)', value: '', unit: 'tonnes', completed: false },
            'burning-oil': { name: 'Burning Oil (litres)', value: '', unit: 'litres', completed: false },
            'biofuel-blend': { name: 'Biofuel Blend %', value: '', unit: '%', completed: false },
        },
        mobileCombustion: {
            'petrol-cars': { name: 'Petrol Cars (litres)', value: '', unit: 'litres', completed: false },
            'diesel-cars': { name: 'Diesel Cars (litres)', value: '', unit: 'litres', completed: false },
            'hybrid-cars': { name: 'Hybrid Cars (litres)', value: '', unit: 'litres', completed: false },
            'lpg-cars': { name: 'LPG Cars (litres)', value: '', unit: 'litres', completed: false },
            'petrol-vans': { name: 'Petrol Vans (litres)', value: '', unit: 'litres', completed: false },
            'diesel-vans': { name: 'Diesel Vans (litres)', value: '', unit: 'litres', completed: false },
            'hgv-diesel': { name: 'HGV Diesel (litres)', value: '', unit: 'litres', completed: false },
            'motorcycles': { name: 'Motorcycles (litres)', value: '', unit: 'litres', completed: false },
        },
        processEmissions: {
            'cement-production': { name: 'Cement Production (tonnes)', value: '', unit: 'tonnes', completed: false },
            'lime-production': { name: 'Lime Production (tonnes)', value: '', unit: 'tonnes', completed: false },
            'glass-production': { name: 'Glass Production (tonnes)', value: '', unit: 'tonnes', completed: false },
            'ammonia-production': { name: 'Ammonia Production (tonnes)', value: '', unit: 'tonnes', completed: false },
            'nitric-acid': { name: 'Nitric Acid (tonnes)', value: '', unit: 'tonnes', completed: false },
        },
        fugitiveEmissions: {
            'r404a': { name: 'R-404A (kg)', value: '', unit: 'kg', completed: false },
            'r410a': { name: 'R-410A (kg)', value: '', unit: 'kg', completed: false },
            'r134a': { name: 'R-134a (kg)', value: '', unit: 'kg', completed: false },
            'r407c': { name: 'R-407C (kg)', value: '', unit: 'kg', completed: false },
            'r32': { name: 'R-32 (kg)', value: '', unit: 'kg', completed: false },
            'co2-refrigerant': { name: 'CO₂ Refrigerant (kg)', value: '', unit: 'kg', completed: false },
        },
    },
    guidance: {
        stationaryCombustion: [
            'Include all fuel used in boilers, furnaces, ovens, generators, and heaters',
            'Natural gas is typically measured in kWh on utility bills',
            'Liquid fuels (diesel, gas oil) are measured in litres',
            'Solid fuels (coal, wood) are measured in tonnes',
            'If using biofuel blends, enter the percentage (e.g., B20 = 20%)',
        ],
        mobileCombustion: [
            'Include all company-owned or leased vehicles',
            'Use fuel purchase records or fuel card data',
            'Separate petrol and diesel consumption',
            'HGVs include lorries, trucks, and heavy goods vehicles',
            "Don't include employee-owned vehicles (that's Scope 3)",
        ],
        processEmissions: [
            'These are chemical reactions, not fuel combustion',
            'Cement: CO₂ released from limestone during production',
            'Lime: CO₂ from calcination of limestone',
            'Glass: CO₂ from soda ash and limestone',
            'Only complete if you have industrial manufacturing processes',
        ],
        fugitiveEmissions: [
            'Include refrigerant leaks from air conditioning and refrigeration',
            'Check service records for refrigerant top-ups (kg)',
            'Different refrigerants have different GWP (Global Warming Potential)',
            'R-404A has very high GWP (use R-32 or R-134a for lower impact)',
            'Include fire suppression systems if applicable',
        ],
    },
}
