export const scope3Config = {
    title: 'Value Chain Indirect Emissions',
    description: 'Enter emissions from your value chain (15 GHG Protocol categories)',
    headerLabel: 'SCOPE 3',
    headerIcon: 'Globe',
    categories: [
        { id: 'purchasedGoods', name: 'Cat 1: Purchased Goods', description: 'Upstream emissions from purchased goods and services', icon: '📦' },
        { id: 'capitalGoods', name: 'Cat 2: Capital Goods', description: 'Long-term assets purchased', icon: '🏗️' },
        { id: 'fuelEnergy', name: 'Cat 3: Fuel & Energy', description: 'Upstream fuel and energy activities', icon: '⛽' },
        { id: 'upstreamTransport', name: 'Cat 4: Upstream Transport', description: 'Inbound logistics and transportation', icon: '🚚' },
        { id: 'waste', name: 'Cat 5: Waste', description: 'Waste generated in operations', icon: '🗑️' },
        { id: 'businessTravel', name: 'Cat 6: Business Travel', description: 'Employee travel for business', icon: '✈️' },
        { id: 'commuting', name: 'Cat 7: Commuting', description: 'Employee commuting to work', icon: '🚗' },
        { id: 'upstreamLeased', name: 'Cat 8: Upstream Leased', description: 'Assets leased by your company', icon: '🏢' },
        { id: 'downstreamTransport', name: 'Cat 9: Downstream Transport', description: 'Outbound logistics and distribution', icon: '📬' },
        { id: 'processing', name: 'Cat 10: Processing', description: 'Processing of intermediate products sold', icon: '⚙️' },
        { id: 'useOfProducts', name: 'Cat 11: Use of Products', description: 'Emissions from customer use of products', icon: '🔌' },
        { id: 'endOfLife', name: 'Cat 12: End-of-Life', description: 'Disposal of products at end of life', icon: '♻️' },
        { id: 'downstreamLeased', name: 'Cat 13: Downstream Leased', description: 'Assets leased to others', icon: '🏘️' },
        { id: 'franchises', name: 'Cat 14: Franchises', description: 'Franchise operations', icon: '🏪' },
        { id: 'investments', name: 'Cat 15: Investments', description: 'Investment portfolio emissions', icon: '💼' },
    ],
    initialData: {
        purchasedGoods: {
            'raw-materials-spend': { name: 'Raw Materials (£)', value: '', unit: '£', completed: false },
            'packaging-materials': { name: 'Packaging Materials (£)', value: '', unit: '£', completed: false },
            'professional-services': { name: 'Professional Services (£)', value: '', unit: '£', completed: false },
            'it-equipment': { name: 'IT Equipment (£)', value: '', unit: '£', completed: false },
            'office-supplies': { name: 'Office Supplies (£)', value: '', unit: '£', completed: false },
        },
        capitalGoods: {
            'buildings-infrastructure': { name: 'Buildings & Infrastructure (£)', value: '', unit: '£', completed: false },
            'machinery-equipment': { name: 'Machinery & Equipment (£)', value: '', unit: '£', completed: false },
            'vehicles-purchased': { name: 'Vehicles Purchased (£)', value: '', unit: '£', completed: false },
        },
        fuelEnergy: {
            'upstream-fuel': { name: 'Upstream Fuel Extraction (kWh)', value: '', unit: 'kWh', completed: false },
            'upstream-electricity': { name: 'Upstream Electricity (kWh)', value: '', unit: 'kWh', completed: false },
            'transmission-losses': { name: 'T&D Losses (kWh)', value: '', unit: 'kWh', completed: false },
        },
        upstreamTransport: {
            'supplier-deliveries-km': { name: 'Supplier Deliveries (tonne-km)', value: '', unit: 'tonne-km', completed: false },
            'inbound-freight': { name: 'Inbound Freight (£)', value: '', unit: '£', completed: false },
            'courier-services': { name: 'Courier Services (£)', value: '', unit: '£', completed: false },
            'shipping-containers': { name: 'Shipping Containers (number)', value: '', unit: 'containers', completed: false },
        },
        waste: {
            'general-waste': { name: 'General Waste (tonnes)', value: '', unit: 'tonnes', completed: false },
            'recycling': { name: 'Recycling (tonnes)', value: '', unit: 'tonnes', completed: false },
            'hazardous-waste': { name: 'Hazardous Waste (tonnes)', value: '', unit: 'tonnes', completed: false },
            'wastewater': { name: 'Wastewater (m³)', value: '', unit: 'm³', completed: false },
        },
        businessTravel: {
            'air-domestic': { name: 'Air Travel - Domestic (km)', value: '', unit: 'km', completed: false },
            'air-short-haul': { name: 'Air Travel - Short Haul (<3700km)', value: '', unit: 'km', completed: false },
            'air-long-haul': { name: 'Air Travel - Long Haul (>3700km)', value: '', unit: 'km', completed: false },
            'rail-travel': { name: 'Rail Travel (km)', value: '', unit: 'km', completed: false },
            'hotel-nights': { name: 'Hotel Nights (number)', value: '', unit: 'nights', completed: false },
        },
        commuting: {
            'car-commute': { name: 'Car Commute (km)', value: '', unit: 'km', completed: false },
            'public-transport': { name: 'Public Transport (km)', value: '', unit: 'km', completed: false },
            'bike-walk': { name: 'Bike/Walk (km)', value: '', unit: 'km', completed: false },
            'remote-working-days': { name: 'Remote Working (days)', value: '', unit: 'days', completed: false },
        },
        upstreamLeased: {
            'leased-vehicles': { name: 'Leased Vehicles (number)', value: '', unit: 'vehicles', completed: false },
            'leased-buildings': { name: 'Leased Buildings (m²)', value: '', unit: 'm²', completed: false },
        },
        downstreamTransport: {
            'product-distribution': { name: 'Product Distribution (tonne-km)', value: '', unit: 'tonne-km', completed: false },
            'customer-deliveries': { name: 'Customer Deliveries (£)', value: '', unit: '£', completed: false },
            'return-logistics': { name: 'Return Logistics (£)', value: '', unit: '£', completed: false },
        },
        processing: {
            'intermediate-products': { name: 'Intermediate Products Sold (tonnes)', value: '', unit: 'tonnes', completed: false },
            'processing-energy': { name: 'Expected Processing Energy (kWh)', value: '', unit: 'kWh', completed: false },
        },
        useOfProducts: {
            'product-units-sold': { name: 'Product Units Sold (number)', value: '', unit: 'units', completed: false },
            'avg-product-lifespan': { name: 'Avg Product Lifespan (years)', value: '', unit: 'years', completed: false },
            'annual-energy-use': { name: 'Annual Energy Use per Product (kWh)', value: '', unit: 'kWh', completed: false },
        },
        endOfLife: {
            'products-landfill': { name: 'Products to Landfill (tonnes)', value: '', unit: 'tonnes', completed: false },
            'products-recycled': { name: 'Products Recycled (tonnes)', value: '', unit: 'tonnes', completed: false },
            'products-incinerated': { name: 'Products Incinerated (tonnes)', value: '', unit: 'tonnes', completed: false },
        },
        downstreamLeased: {
            'properties-leased-out': { name: 'Properties Leased to Others (m²)', value: '', unit: 'm²', completed: false },
            'equipment-leased-out': { name: 'Equipment Leased to Others (number)', value: '', unit: 'items', completed: false },
        },
        franchises: {
            'franchise-locations': { name: 'Franchise Locations (number)', value: '', unit: 'locations', completed: false },
            'franchise-revenue': { name: 'Total Franchise Revenue (£)', value: '', unit: '£', completed: false },
        },
        investments: {
            'equity-investments': { name: 'Equity Investments (£)', value: '', unit: '£', completed: false },
            'debt-investments': { name: 'Debt Investments (£)', value: '', unit: '£', completed: false },
            'project-finance': { name: 'Project Finance (£)', value: '', unit: '£', completed: false },
        },
    },
    guidance: {
        purchasedGoods: [
            'Use spend-based method: Total spend (£) × DEFRA emission factor for product category',
            'Get data from procurement records and invoices',
            'Separate by material type for accuracy (metals, plastics, paper, etc.)',
            'Don\'t include capital goods (buildings, machinery) - use Category 2',
        ],
        businessTravel: [
            'Domestic flights: <500 km one-way',
            'Short-haul: 500-3700 km (e.g., within Europe)',
            'Long-haul: >3700 km (intercontinental)',
            'Get data from travel booking systems or expense reports',
            'Include hotel nights using DEFRA hotel emission factors',
        ],
        commuting: [
            'Survey employees for commute distance and mode',
            'Multiply by working days (e.g., 220 days/year)',
            'Remote working reduces commuting emissions',
            'Include working from home emissions for remote workers',
        ],
        waste: [
            'Get data from waste contractor invoices (tonnes per waste stream)',
            'Separate by disposal method: landfill, recycling, incineration, composting',
            'Recycling has lower emissions than landfill',
            'Include wastewater treatment if applicable',
        ],
        useOfProducts: [
            'Estimate based on product units sold and typical usage patterns',
            'Get average product lifespan from manufacturer specs',
            'For electrical products, estimate annual kWh usage',
            'Consider end-of-life disposal (landfill vs recycling)',
            'This category often requires assumptions - document methodology',
        ],
        endOfLife: [
            'Estimate based on product units sold and typical usage patterns',
            'Get average product lifespan from manufacturer specs',
            'For electrical products, estimate annual kWh usage',
            'Consider end-of-life disposal (landfill vs recycling)',
            'This category often requires assumptions - document methodology',
        ],
        investments: [
            'For financial institutions: emissions from investment portfolio',
            'Use PCAF (Partnership for Carbon Accounting Financials) methodology',
            'Equity share approach: (Your investment / Total equity) × Investee emissions',
            'Request emissions data from investee companies',
        ],
    },
}
