version: '3.8'

services:
  # PostgreSQL Database (Development)
  postgres-dev:
    image: postgres:15-alpine
    container_name: carbon-depict-db-dev
    environment:
      POSTGRES_USER: carbonuser
      POSTGRES_PASSWORD: carbonpass123
      POSTGRES_DB: carbondepict_dev
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
      - ./server/database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - carbon-depict-dev-network

  # MongoDB (Development)
  mongodb-dev:
    image: mongo:7-jammy
    container_name: carbon-depict-mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: carbonadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass123
      MONGO_INITDB_DATABASE: carbondepict_dev
    volumes:
      - mongodb-dev-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - carbon-depict-dev-network

  # Redis (Development)
  redis-dev:
    image: redis:7-alpine
    container_name: carbon-depict-redis-dev
    command: redis-server --requirepass redispass123
    ports:
      - "6379:6379"
    networks:
      - carbon-depict-dev-network

  # Backend API (Development with hot reload)
  backend-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: carbon-depict-api-dev
    environment:
      NODE_ENV: development
      PORT: 5500
      POSTGRES_HOST: postgres-dev
      POSTGRES_PORT: 5432
      POSTGRES_USER: carbonuser
      POSTGRES_PASSWORD: carbonpass123
      POSTGRES_DB: carbondepict_dev
      MONGO_URI: mongodb://carbonadmin:mongopass123@mongodb-dev:27017/carbondepict_dev?authSource=admin
      REDIS_HOST: redis-dev
      REDIS_PORT: 6379
      REDIS_PASSWORD: redispass123
      JWT_SECRET: dev-secret-key-not-for-production
      JWT_EXPIRE: 7d
      CORS_ORIGIN: http://localhost:3500
    depends_on:
      - postgres-dev
      - mongodb-dev
      - redis-dev
    ports:
      - "5500:5500"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
      - ./server/logs:/app/logs
    networks:
      - carbon-depict-dev-network

  # Frontend Application (Development with hot reload)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: carbon-depict-app-dev
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:5500/api
    depends_on:
      - backend-dev
    ports:
      - "3500:3500"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - carbon-depict-dev-network
    stdin_open: true
    tty: true

volumes:
  postgres-dev-data:
  mongodb-dev-data:

networks:
  carbon-depict-dev-network:
    driver: bridge
